# Generated by Django 5.0.3 on 2024-04-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cu_id', models.AutoField(primary_key=True, serialize=False)),
                ('cu_name', models.CharField(max_length=100)),
                ('cu_phonenumber', models.CharField(max_length=11)),
                ('cu_email', models.EmailField(blank=True, max_length=254)),
                ('cu_location', models.CharField(max_length=40)),
            ],
        ),
    ]
