# Generated by Django 5.0.3 on 2024-04-11 14:14

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('cu_id', models.AutoField(primary_key=True, serialize=False)),
                ('cu_name', models.CharField(max_length=100)),
                ('cu_phonenumber', models.CharField(max_length=11)),
                ('cu_email', models.EmailField(blank=True, max_length=254)),
                ('cu_location', models.CharField(max_length=40)),
                ('cu_password', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
