# Generated by Django 5.0.3 on 2024-04-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cu_phonenumber',
        ),
    ]
