# Generated by Django 5.0.3 on 2024-04-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cu_password',
            field=models.CharField(default='1234', max_length=128),
            preserve_default=False,
        ),
    ]
