# Generated by Django 5.0.3 on 2024-04-13 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_options_alter_customer_cu_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cu_email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
