# Generated by Django 5.0.3 on 2024-05-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
