# Generated by Django 5.0.3 on 2024-05-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlogTitle', models.CharField(max_length=50)),
                ('BlogDescription', models.TextField()),
                ('BlogType', models.CharField(max_length=50)),
                ('BlogImage', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('SeoTitle', models.CharField(blank=True, max_length=50, null=True)),
                ('SeoDescription', models.CharField(blank=True, max_length=50, null=True)),
                ('SeoKeywords', models.CharField(blank=True, max_length=50, null=True)),
                ('SeoIndexpage', models.BooleanField(blank=True, default=False, null=True)),
                ('SeoCanonical', models.URLField(blank=True, null=True)),
                ('SeoSchema', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
