# Generated by Django 5.0.3 on 2024-04-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=50)),
                ('b_text', models.TextField()),
                ('b_type', models.CharField(choices=[('music', 'music'), ('show', 'show'), ('cinema', 'cinema')], max_length=9)),
                ('b_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('SeoTitle', models.CharField(max_length=50)),
                ('SeoDescription', models.CharField(max_length=50)),
                ('SeoKeywords', models.CharField(max_length=50)),
                ('SeoIndexpage', models.BooleanField(default=False)),
                ('SeoCanonical', models.URLField()),
                ('SeoSchema', models.URLField()),
            ],
        ),
    ]
