# Generated by Django 5.0.3 on 2024-06-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='BlogType',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Concert', 'Concert'), ('Music', 'Music')], max_length=50),
        ),
    ]
