# Generated by Django 5.0.3 on 2024-04-17 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='Blog',
        ),
    ]
