# Generated by Django 5.0.3 on 2024-04-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_b_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='SeoCanonical',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='SeoDescription',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='SeoIndexpage',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='SeoKeywords',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='SeoSchema',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='SeoTitle',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
