# Generated by Django 5.0.3 on 2024-04-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_seocanonical_alter_blog_seodescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='SeoCanonical',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='SeoDescription',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='SeoIndexpage',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='SeoKeywords',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='SeoSchema',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='SeoTitle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='b_type',
            field=models.CharField(choices=[('music', 'music'), ('show', 'show'), ('cinema', 'cinema')], max_length=9),
        ),
    ]
