# Generated by Django 5.0.3 on 2024-04-22 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sans',
            name='co_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.concert'),
        ),
    ]
