# Generated by Django 5.0.3 on 2024-05-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='NumberofRows',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seat',
            name='SeatRow',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
