# Generated by Django 5.0.3 on 2024-04-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='co_seats',
        ),
    ]
