# Generated by Django 5.0.3 on 2024-04-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='co_status',
            field=models.CharField(choices=[('Soldout', 'Soldout'), ('active', 'active')], default='active', max_length=20),
        ),
    ]
