# Generated by Django 5.0.3 on 2024-05-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_sans_sanstime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='ConcertDate',
            field=models.DateField(max_length=20),
        ),
    ]
