# Generated by Django 5.0.3 on 2024-04-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_concert_co_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='se_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
