# Generated by Django 5.0.3 on 2024-05-16 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_concert_numberofrows_alter_seat_seatrow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rows',
            old_name='ConcertId',
            new_name='Concert',
        ),
    ]
