# Generated by Django 5.0.3 on 2024-04-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_concert_co_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='co_type',
            field=models.CharField(choices=[('music', 'music'), ('show', 'show')], default='music', max_length=250),
        ),
    ]
