# Generated by Django 5.0.3 on 2024-04-24 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_sans_co_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='se_status',
            field=models.CharField(choices=[('Empty', 'Empty'), ('Reserved', 'Reserved'), ('Reserving', 'Reserving'), ('not_buyable', 'not_buyable'), ('selected', 'selected')], default='Empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='co_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.concert'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sa_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.sans'),
        ),
    ]
