# Generated by Django 5.0.3 on 2024-05-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_concert_concertdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='SansId',
        ),
    ]
