# Generated by Django 5.0.3 on 2024-05-16 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_concertid_rows_concert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rows',
            old_name='Concert',
            new_name='ConcertId',
        ),
    ]
