# Generated by Django 5.0.3 on 2024-04-09 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_concert_co_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cu_location',
            field=models.CharField(default='Tabriz', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concert',
            name='a_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='concert',
            name='co_date',
            field=models.DateTimeField(max_length=20),
        ),
        migrations.AlterField(
            model_name='concert',
            name='co_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='concert',
            name='co_type',
            field=models.CharField(choices=[('music', 'music'), ('show', 'show'), ('cinema', 'cinema')], default='music', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cu_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cu_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cu_phonenumber',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=9),
        ),
        migrations.AlterField(
            model_name='sans',
            name='co_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.concert'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='se_area',
            field=models.CharField(blank=True, choices=[('VIP', 'VIP'), ('balcony', 'balcony'), ('simple', 'simple')], max_length=7),
        ),
        migrations.AlterField(
            model_name='seat',
            name='se_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='se_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.seat'),
        ),
    ]
