# Generated by Django 5.0.3 on 2024-04-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_seat_se_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='se_max_price',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='se_min_price',
        ),
        migrations.AddField(
            model_name='seat',
            name='from_seat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='to_seat',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seat',
            name='se_row',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='se_status',
            field=models.CharField(choices=[('Empty', 'Empty'), ('Reserved', 'Reserved'), ('Reserving', 'Reserving'), ('not_buyable', 'not_buyable')], default='Empty', max_length=20),
        ),
    ]
