# Generated by Django 5.0.3 on 2024-04-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customer_cu_location_alter_concert_a_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
