# Generated by Django 5.0.3 on 2024-05-19 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_concert_rows_concertid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='Rowid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Row_Number', to='home.rows'),
        ),
    ]
