# Generated by Django 5.0.3 on 2024-04-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='co_location',
            field=models.CharField(default='tabriz', max_length=40),
            preserve_default=False,
        ),
    ]
