# Generated by Django 5.0.3 on 2024-04-30 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_concert_num_seats_seat_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='co_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Concert_name', to='home.concert'),
        ),
    ]
