# Generated by Django 5.0.3 on 2024-06-04 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='ConcertId',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='home.concert'),
            preserve_default=False,
        ),
    ]
