# Generated by Django 5.0.3 on 2024-04-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_concert_co_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='co_status',
            field=models.CharField(choices=[('Soldout', 'Soldout'), ('Active', 'Active'), ('ComingSoon', 'ComingSoon')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('canceled', 'canceled')], default='Pending', max_length=9),
        ),
        migrations.AlterField(
            model_name='seat',
            name='se_status',
            field=models.CharField(choices=[('Empty', 'Empty'), ('Reserved', 'Reserved'), ('Reserving', 'Reserving'), ('noy_buyable', 'noy_buyable')], default='Empty', max_length=20),
        ),
    ]
