# Generated by Django 5.0.3 on 2024-04-30 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_seat_co_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='customer',
        ),
    ]
