# Generated by Django 5.0.3 on 2024-05-19 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_seat_rowid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='Rowid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Concert_name', to='home.rows'),
        ),
    ]
