# Generated by Django 5.0.3 on 2024-05-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_seat_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concert',
            old_name='num_seats',
            new_name='num_rows',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='from_seat',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='to_seat',
        ),
        migrations.AddField(
            model_name='concert',
            name='num_seats_in_rows',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concert',
            name='row_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
