# Generated by Django 5.0.3 on 2024-04-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_concert_co_status_alter_payment_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='t_serial',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
