# Generated by Django 5.0.3 on 2024-05-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_seat_rowid'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='NumberofSeat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
