# Generated by Django 5.0.3 on 2024-06-06 22:22

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_rows_rowarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='sans',
            name='SansDate',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sans',
            name='SansStatus',
            field=models.CharField(choices=[('Active', 'Active'), ('Soldout', 'Soldout')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='concert',
            name='ConcertDate',
            field=django_jalali.db.models.jDateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='PaymentDate',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
    ]
