# Generated by Django 5.0.3 on 2024-05-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_seat_numberofseat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='SeatNumber',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
