# Generated by Django 5.0.3 on 2024-05-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_seat_seatnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='SeatNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
