# Generated by Django 5.0.3 on 2024-05-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_seat_numberofseat_remove_seat_seatarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='ConcertStatus',
            field=models.CharField(choices=[('Soldout', 'Soldout'), ('Active', 'Active'), ('ComingSoon', 'ComingSoon')], default='ComingSoon', max_length=20),
        ),
    ]
