# Generated by Django 5.0.3 on 2024-05-21 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_concert_concertstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='sans',
            name='SeatId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.seat'),
            preserve_default=False,
        ),
    ]
