# Generated by Django 5.0.3 on 2024-05-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_sans_seatid'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='SeatPrice',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
