# Generated by Django 5.0.3 on 2024-05-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_seat_seatprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rows',
            name='RowPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='SeatPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
